version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - data:/opt/oracle/oradata
    deploy:
      replicas: 1

volumes:
  data: